apiVersion: v1
kind: Service
metadata:
  name: tampere-virtualmonitor-service
spec:
  ports:
  - name: "virtualmonitor-entrypor"
    port: 80
    targetPort: 3000
  selector:
    app: tampere-virtualmonitor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tampere-virtualmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tampere-virtualmonitor
  template:
    metadata:
      labels:
        app: tampere-virtualmonitor
    spec:
      containers:
      - name: <TODO>
        image: <TODO>
        imagePullPolicy: "Always"
        ports: 
         - containerPort: 3000
---  